name             'clojure-stack'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures clojure-stack'
long_description 'Installs/Configures clojure-stack'
version          '0.1.0'

depends 'apt'
depends 'git'
depends 'build-essential'
depends 'ruby_build'
depends 'nodejs'
depends 'vim'
depends 'mysql', '~> 6.0'
depends 'nginx'
depends 'mongodb', '~> 0.16.2'
depends 'java', '~> 1.31.0'
